### ISSUE TITLE
Incorrect sample link for Proxy server

### ISSUE THREAD

**Issue by djbrown** [plantuml/plantuml.com#18]
### Concerning Page

https://plantuml.com/en/server
section "Proxy service"

### Problem

wrong link currently: http://www.plantuml.com/plantuml/proxy?idx=1&src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test2diagrams.txt

problem 1: the file was moved (see [file history](https://github.com/plantuml/plantuml-server/commits/master/src/main/webapp/resource/test/test2diagrams.txt)) to a subdirectory `test`.
solution: add subdirectory to url: `resouce/test/test2diagrams.txt`

problem 2: there is only one diagram in the file, `idx` starts at 0, so `idx=1` fails
solution: remove `idx=1&` part from the url, default is 0 anyways

### Solution
**correct** link would be: http://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test/test2diagrams.txt

### Additional context

- I tried to fix this via http://alphadoc.plantuml.com/doc/markdown/en/server#cml3g41qyodck362kjmf
but saving didn't do anything and I couldn't find any docs for the alphadocs tool. is it only for admins, or does it trigger some review?
- should also be fixed for other languages
- also might be relevant for #7

**Comment by arnaudroques** [comment]
> * I tried to fix this via http://alphadoc.plantuml.com/doc/markdown/en/server#cml3g41qyodck362kjmf
>   but saving didn't do anything and I couldn't find any docs for the alphadocs tool. is it only for admins, or does it trigger some review?

Thank you for highlighting this issue and for your attempts to enhance our documentation!

We're pleased to inform you that we have updated [our website based on your change](https://plantuml.com/en/server). It's important to note that changes submitted through our system don't take effect immediately because we employ a review process. Since the access is free, we have to be vigilant about spam :-)

Should you come across any additional issues or have more suggestions, we encourage you to reach out or make those changes directly.

Thanks again,

Arnaud

**Comment by djbrown** [comment]
Thanks :) I also fixed [japanese](http://alphadoc.plantuml.com/cmp/markdown/ja/server#cml3g41qyodck362kjmf) so its fixed for all languages
